services:
  - type: web
    name: bfhl-api
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/bfhl-0.0.1-SNAPSHOT.jar
    envVars:
      - key: APP_USER_FULL_NAME
        value: Sarthak Sharma
      - key: APP_USER_DOB
        value: DDMMYYYY
      - key: APP_USER_EMAIL
        value: your_email@chitkara.edu.in
      - key: APP_USER_ROLL_NUMBER
        value: YOUR_ROLL_NUMBER
